spring:
  application:
    name: Spring-Security-Study
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/atguigu
      username: root
      password: lixiang[666]
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

